### ISSUE TITLE
Shared library in a plugin

### ISSUE THREAD

**Issue by fsher** [miyako/4d-plugin-wizard#1]
Hello Miyako,

Thank you for all your work!

I am trying to create a plugin for 4D, which uses a shared library (.so). The library was created for 32 and 64-bit architectures. XCode should have linked them automatically.

I got 2 warnings during the build:
`ld: warning: ignoring file /***/***_32.so, file was built for i386 which is not the architecture being linked (x86_64): /***/***_32.so`
And the same one for the 64bit.

Eventually 4D can't execute my plugin. Mac's console states that "image not found" even though I made XCode copy the library files into the bundle.

I don't understand, why it's linking the libraries so oddly.

I would really appreciate your help!
Thank you!

_XCode 7.3.1
4D v15 R4
Project Settings are from the repo._

**UPDATE**
So I removed the 32bit version of the library and set XCode project only to build for 64bit.
Now it's building without any warnings. But still, 4D Server is not loading the shared library.

**Comment by miyako** [comment]
you can combine your 2 libraries into a single file and link against that universal binary.

`lipo -create ***_32.so ***_64.so -output ***.so`

**Comment by fsher** [comment]
Thank you! That fixed half of the problem. Now 4D Server still cant find the shared library.
Eventually I figured out that OS X has a folder with all dynamic libraries. A moved mine to it and the server started with no errors.

The only thing, that's bothering me is why it can't load the .so from the bundle?

**Comment by miyako** [comment]
normally I use dynamic libraries (dylib), not shared libraries.
dylibs have an install name, which is normally the path,
which you can check with `otool -L`
normally I change it to a relative path with 
`install_name_tool -id @loader_path/...` in case of a plugin,
because `@excutable_path` would resolve against the main bundle path, not the plugin.

**Comment by fsher** [comment]
Thank you! I really appreciate it!
