### ISSUE TITLE
Compile for 64 Bit

### ISSUE THREAD

**Issue by christianschneider89** [miyako/4d-plugin-wizard#2]
Hello

I tried to compile for 64bit Windows. I got a lot of "possible loss of data" and a "fatal error LNK1120: 14 unresolved externals".

Here the output log:

`1>------ Build started: Project: Pepper_V16, Configuration: Release x64 ------`
`1>  ARRAY_BOOLEAN.cpp`
`1>  ARRAY_INTEGER.cpp`
`1>  ARRAY_LONGINT.cpp`
`1>  ARRAY_REAL.cpp`
`1>  ARRAY_TEXT.cpp`
`1>4D Plugin API\Classes\ARRAY_TEXT.cpp(86): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data`
`1>4D Plugin API\Classes\ARRAY_TEXT.cpp(90): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data`
`1>4D Plugin API\Classes\ARRAY_TEXT.cpp(112): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data`
`1>4D Plugin API\Classes\ARRAY_TEXT.cpp(116): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data`
`1>  C_BLOB.cpp`
`1>4D Plugin API\Classes\C_BLOB.cpp(61): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data`
`1>4D Plugin API\Classes\C_BLOB.cpp(99): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data`
`1>4D Plugin API\Classes\C_BLOB.cpp(177): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data`
`1>4D Plugin API\Classes\C_BLOB.cpp(189): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data`
`1>  C_DATE.cpp`
`1>  C_INTEGER.cpp`
`1>  C_LONGINT.cpp`
`1>  C_PICTURE.cpp`
`1>  C_POINTER.cpp`
`1>  C_REAL.cpp`
`1>  C_TEXT.cpp`
`1>4D Plugin API\Classes\C_TEXT.cpp(161): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data`
`1>4D Plugin API\Classes\C_TEXT.cpp(165): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data`
`1>4D Plugin API\Classes\C_TEXT.cpp(187): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data`
`1>4D Plugin API\Classes\C_TEXT.cpp(191): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data`
`1>  C_TIME.cpp`
`1>  4DPlugin.cpp`
`1>4DPlugin.cpp(257): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(258): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(284): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(285): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(308): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(329): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(330): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(377): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(378): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(379): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(380): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(381): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(382): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(383): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(384): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(499): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(500): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(501): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(502): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(503): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(504): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(505): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(506): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(507): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(508): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(509): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(510): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(511): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(512): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(513): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(514): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(515): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(561): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(586): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(620): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(621): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>4DPlugin.cpp(640): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data`
`1>  4DPluginAPI.cpp`
`1>4D Plugin API\4DPluginAPI.cpp(7532): warning C4244: '=': conversion from 'sLONG_PTR' to 'PA_long32', possible loss of data`
`1>     Creating library .\Pepper_V16.4dbase\plugins\Pepper_V16.bundle\contents\windows64\Pepper_V16.lib and object .\Pepper_V16.4dbase\plugins\Pepper_V16.bundle\contents\windows64\Pepper_V16.exp`
`1>4DPlugin.obj : error LNK2001: unresolved external symbol __imp_eftCleanupDriver`
`1>4DPlugin.obj : error LNK2001: unresolved external symbol __imp_eftOpen`
`1>4DPlugin.obj : error LNK2001: unresolved external symbol __imp_eftInitializeLibrary`
`1>4DPlugin.obj : error LNK2001: unresolved external symbol __imp_eftEndOfDay`
`1>4DPlugin.obj : error LNK2001: unresolved external symbol __imp_eftClose`
`1>4DPlugin.obj : error LNK2001: unresolved external symbol __imp_eftVersion`
`1>4DPlugin.obj : error LNK2001: unresolved external symbol __imp_eftConfigDriver`
`1>4DPlugin.obj : error LNK2001: unresolved external symbol __imp_eftTrx`
`1>4DPlugin.obj : error LNK2001: unresolved external symbol __imp_eftFinalizeLibrary`
`1>4DPlugin.obj : error LNK2001: unresolved external symbol __imp_eftStatus`
`1>4DPlugin.obj : error LNK2001: unresolved external symbol __imp_eftInit`
`1>4DPlugin.obj : error LNK2001: unresolved external symbol __imp_eftGetTerminal`
`1>4DPlugin.obj : error LNK2001: unresolved external symbol __imp_eftInitializeLibraryWithConfig`
`1>4DPlugin.obj : error LNK2001: unresolved external symbol __imp_eftUtility`
`1>.\Pepper_V16.4dbase\plugins\Pepper_V16.bundle\contents\windows64\Pepper_V16.4DX : fatal error LNK1120: 14 unresolved externals`
`========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`
`

How to compile it for Windows 64 Bit?

Thanks!
Chris

**Comment by miyako** [comment]
as for the **warnings**, do a search on the warning code or the message itself, then you can decide to suppress, ignore, or fix them. none of of them are critical, and **none of them are blocking the compilation**.

as for the **errors**, it seems your visual c project is not configured right.

perhaps your **pre-compiler flags** are wrong (search **__declspec dllexport, dllimport**) or the imported libraries were built with the wrong **default library**, or the **link-time code optimisation** is incorrect, or you are not **importing the necessary libraries** to begin with, or you are trying to link a c object with a c++ object... 

whatever the case, it is not a problem of the SDK.

**Comment by miyako** [comment]
to save time, you can request professional services to 4D Japan (Info-JP@4D.com) to study your project and compile it (if technically possible) for 64-bit.
